routes:
  - uri: /*
    upstream:
      nodes:
        "myapp:8080": 1
    plugins:
      openid-connect:
        discovery: ${{KEYCLOAK_URL:=}}/realms/apisix/.well-known/openid-configuration
        client_id: apisix
        client_secret: ${{KEYCLOAK_CLIENT_SECRET:=}}
        bearer_only: false
        scope: openid
        realm: apisix
        redirect_uri: http://localhost:9080/callback
#END
